[package]
name = "rust-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
futures = "0.3.30"
num_cpus = "1.16.0"
tokio = { version = "1.38.1", features = ["full"] }
tokio-macros = "2.3.0"
